### PR TITLE
Added version to package.json and changed url-s

### PR DESCRIPTION
**Pull request by BojanKogoj**

### CODE REVIEW

**Comment by BojanKogoj** [comment]
I added version, otherwise I wan't able to add it as dependency in my project.

**Comment by bwinton** [comment]
(I'm also not entirely convinced that this is the package you want to import, vs. something new we put under the `design-tokens` repo, that this ends up using. @aminalhazwani, what do you think is the right solution here?)

**Comment by BojanKogoj** [comment]
If it were in design-tokens even better, already have that as a dependency. But right now it seems this is the only way to get icons (I'd like to _photonize_ my plugins as soon as possible)

**Comment by bwinton** [comment]
For now, I'd recommend just copying the icons you want to use, then, and when the design-tokens repo gets updated, you can switch over to use that. 🙂

**Comment by nt1m** [comment]
You might want to update the name of the package as well.

**Comment by BojanKogoj** [comment]
@nt1m To what name? 
@bwinton I'm not sure manually copy-pasting is wise, once it gets merged into design-tokens I can simply switch dependency and imports and that's it.

**Comment by nt1m** [comment]
I would suggest photon-icons as name, but maybe @bwinton might have a better idea.

**Comment by bwinton** [comment]
https://www.npmjs.com/package/photon-icons :)

**Comment by BojanKogoj** [comment]
I suppose #13 can be closed now.

**Pull request merged**
