### PR TITLE
Get it working with the imported icons.

### PR DESCRIPTION
**Pull request by bwinton**
Hey Tim and Erica,

we're starting to export some icons from the photon design system, and ideally eventually use those to generate this site. How does this code look to you? Understandable? Any changes you'd recommend?

### CODE REVIEW

**Comment by aminalhazwani** [comment]
@ericawright @nt1m do you folks have any feedback? Thank you very much 🙇 For more context see https://github.com/FirefoxUX/design-tokens/tree/master/photon-icons

**Comment by nt1m** [comment]
The general approach looks ok to me, I'm just wondering if we can't simplify this further by not having a deployment script and simply fetching the icons+listing directly from npm.

**Comment by bwinton** [comment]
Okay, I _think_ this is ready for the actual review. Have at it, everyone! 😃

(@nt1m I think I agree that we can use the icons+listing directly from npm. But I'd like to make that a followup bug, if you don't mind.)

**Comment by bwinton** [comment]
screenshot

**Comment by bwinton** [comment]
> * $ npm run dev prompts an error

No it doesn't. 😉  (It's impossible for me to do anything with this unless you paste the error you're seeing…)

> * once we merge FirefoxUX/photon-icons#1 we can problably bump the npm version to v3.1.0

Done.

> * we can remove the /viewer subfolder, feel free to open a following issue

I'll let someone else open that issue, if they feel strongly.

> * what is the difference between /dist and /html

`/dist` is where the generated files go. `/html` is the source.

> * there's an empty folder /icons/extensions

Not anymore. 😃

> * we can remove most of the contents from the README.md

I think it's still kinda useful, so I don't really want to do that.

> * with $ npm run watch, if I select an icon in the grid list, the sidebar opens, but the icon is not displayed in the preview

That would depend on how you're starting the server, I suppose. Maybe try the new `npm run dev` and see if it's better, or if not, paste the location of the missing image here so I can see why it's missing…

**Comment by aminalhazwani** [comment]
> No it doesn't. 😉 (It's impossible for me to do anything with this unless you paste the error you're seeing…)

It works, I was kidding!

> I'll let someone else open that issue, if they feel strongly.

I edited the comment above, we already had an issue, see #43

> I think it's still kinda useful, so I don't really want to do that.

I agree that is useful, but this is not the place where this information is _most_ useful. As you said [here](https://github.com/FirefoxUX/icons/issues/68#issuecomment-390221629) we should have info and request specifically to the website, not the icons them self, let me open an issue to address this if it sounds good to you!

> That would depend on how you're starting the server, I suppose. Maybe try the new npm run dev and see if it's better, or if not, paste the location of the missing image here so I can see why it's missing…

Yes, thanks Blake!

**Pull request merged**
