### PR TITLE
Add Photon Branding Icons

### PR DESCRIPTION
**Pull request by ExE-Boss**
### Icons copied from:
- https://hg.mozilla.org/mozilla-central/file/39f4a41bb708/browser/branding/official/content/identity-icons-brand.svg ([mozilla/gecko-dev#browser/official/content/identity-icons-brand.svg](https://github.com/mozilla/gecko-dev/blob/a2102f9d0936c3ae67c76e5141026f4b46134424/browser/branding/official/content/identity-icons-brand.svg))
- https://hg.mozilla.org/mozilla-central/file/6f08f91f8db0/browser/branding/aurora/content/identity-icons-brand.svg ([mozilla/gecko-dev#browser/aurora/content/identity-icons-brand.svg](https://github.com/mozilla/gecko-dev/blob/a2102f9d0936c3ae67c76e5141026f4b46134424/browser/branding/aurora/content/identity-icons-brand.svg))
- https://hg.mozilla.org/mozilla-central/file/86789f3d0818/browser/branding/nightly/content/identity-icons-brand.svg ([mozilla/gecko-dev#browser/nightly/content/identity-icons-brand.svg](https://github.com/mozilla/gecko-dev/blob/a2102f9d0936c3ae67c76e5141026f4b46134424/browser/branding/nightly/content/identity-icons-brand.svg))

### CODE REVIEW

**Comment by bwinton** [comment]
Sweet, thank you! 😃

Once we have a smaller DevEdition logo, we should throw that in there, too…

**Comment by aminalhazwani** [comment]
@ExE-Boss where are these product icon glyphs used?

**Comment by nt1m** [comment]
@aminalhazwani They're used in the identity block when you're on an internal page (about:preferences).

**Comment by aminalhazwani** [comment]
@nt1m thank you! Ok, seen the usage I am not really sure these icons belong here. It is a very specific case (considering also the gradient fill). Maybe the flay grey one (the one used in about:newtab) but dunno about those. Let me circle back to the Photon people in order to understand if there are other possible usage/applications.

**Pull request merged**
